### ISSUE TITLE
Create data node stored in European servers

### ISSUE THREAD

**Issue by DominiqueMakowski** [jspsych/datapipe#92]
In order to accommodate European data protection laws that regulate most of European universities, OSF lets us select severs located within the EU (Germany). However, by default, datapipe creates a US-based storage node, regardless of the location of the parent project. 
Would it be able to add the option to change that?

![image](https://github.com/jspsych/datapipe/assets/8875533/d50772bb-3920-41a2-ae8a-fd4b309a8804)

**Comment by francesco-vespignani** [comment]
This issue prevents me also from using datapipe, which I'd love to. EU regulation is rather strict on this. I gave a look to the osf api doc and it seems to me that there is no attribute allowing to tell where to create a child node. Probably the OSF  storage is automatically created in US or on the basis of the ip of the call. I looked at possible workarounds but probably the easy solution I see is to allow the enduser to enter a specific component instead of asking datapipe to create it.  It would be less elegant than now (having a whole component created by scratch).

**Comment by jodeleeuw** [comment]
Thanks for raising this. I'm going to try and work on it sometime in the next two weeks.

**Comment by jodeleeuw** [comment]
I think I've found a way to do this through the OSF API. It may be a few more days before I'm able to implement the changes, but I'm working on it!

**Comment by jodeleeuw** [comment]
All set! Give it a try and lemme know if you run into any issues.

![image](https://github.com/jspsych/datapipe/assets/595524/ae1c3456-deed-47fd-b42a-c4de847a4dab)

**Comment by DominiqueMakowski** [comment]
Seems to work, cheers @jodeleeuw !

**Comment by francesco-vespignani** [comment]
Thanks so much Josh !!!
